services:
  db:
    image: postgres:15.2
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust

  datadog:
    image: datadog/agent:7.42.1
    environment:
      - DD_API_KEY=${DD_API_KEY}
      - DD_ENV=${USER}-local
      - DD_DOGSTATSD_SOCKET=/var/run/dogstatsd/dogstatsd.sock
      - DD_APM_ENABLED=true
      - DD_BIND_HOST=0.0.0.0
    volumes:
      - /var/run/dogstatsd:/var/run/dogstatsd
      - /var/run/docker.sock:/var/run/docker.sock
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup:/host/sys/fs/cgroup:ro
    ports:
      - "8126:8126"
      - "8125:8125/udp"
